#!/usr/bin/env python3
"""Generate the GitHub Pages site in docs/ from the skill's own reference files.

The skill files are the single source of truth. This script copies them into
docs/ with Jekyll front matter, so each becomes a page with its own URL, title
and meta description — which is the whole reason for publishing them rather than
leaving them as Markdown three folders deep, where search engines index them
weakly and render no title at all.

Titles and descriptions here are deliberately written against the phrases people
actually search when a Paynow integration breaks ("hash mismatch", "paid but not
fulfilled", "status.paid is not a function"), not against product names. Nobody
googles "paynow integration library"; they paste the symptom.

    python3 tools/build_docs.py          # regenerate
    python3 tools/build_docs.py --check  # exit 1 if docs/ is stale (used by CI)
"""

import argparse
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFS = os.path.join(ROOT, "paynow-skills", "paynow-integration", "references")
DOCS = os.path.join(ROOT, "docs")

BANNER = "# GENERATED by tools/build_docs.py - edit the source file, then re-run it."

# source, permalink, <title>, meta description, optional lede
PAGES = [
    (
        os.path.join(REFS, "hashing.md"),
        "/hashing/",
        "Paynow hash mismatch: generating and validating SHA-512",
        "Why Paynow hashes mismatch and how to fix it: field order, URL-decoding, "
        "hashing every returned value, and lower-casing the integration key.",
        "Almost every \u201cPaynow isn\u2019t working\u201d report is a hashing bug. Prove the "
        "helper against the two fixtures below and the whole class of failure disappears.",
    ),
    (
        os.path.join(REFS, "troubleshooting.md"),
        "/troubleshooting/",
        "Paynow troubleshooting: hashes, callbacks, unfulfilled orders",
        "Symptom-to-cause table for Paynow Zimbabwe: hash mismatches, callbacks that "
        "never arrive, and orders marked paid that are never fulfilled.",
        "Start here when something is broken. Most Paynow problems are one of about a "
        "dozen things, and the symptom usually points straight at the cause.",
    ),
    (
        os.path.join(REFS, "php-laravel.md"),
        "/php-laravel/",
        "Paynow with PHP and Laravel: SDK, exceptions, wiring",
        "Integrating Paynow in PHP and Laravel: the SDK's API, the exceptions it throws, "
        "why paid() does not mean paid, and complete controller wiring.",
        None,
    ),
    (
        os.path.join(REFS, "nodejs-express.md"),
        "/nodejs-express/",
        "Paynow with Node.js and Express: SDK defects and fixes",
        "Integrating Paynow in Node.js and Express: why status.paid() throws, why "
        "pollTransaction must be awaited, and a raw client for InnBucks.",
        None,
    ),
    (
        os.path.join(REFS, "raw-http.md"),
        "/raw-http/",
        "Paynow HTTP API: endpoints, fields and status values",
        "The Paynow Zimbabwe HTTP interface for any language: endpoints, request fields, "
        "status values, Express Checkout and the status-update callback.",
        "Use this for any language without an official SDK, and for the Express Checkout "
        "methods the PHP and Node SDKs don\u2019t wrap.",
    ),
    (
        os.path.join(REFS, "testing-and-golive.md"),
        "/testing/",
        "Paynow test mode: test numbers, tokens and go-live",
        "Testing Paynow: the merchant-account rule that blocks your own test payments, "
        "the four EcoCash test numbers, card tokens, and the go-live checklist.",
        None,
    ),
]


def read(path):
    return io.open(path, encoding="utf-8").read().replace("\r\n", "\n")


def yaml_quote(s):
    return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')


def transform(body, self_permalink):
    """Strip the H1 (the layout renders it) and turn backticked file references
    into real links, so a reader on the site can actually follow them."""
    body = re.sub(r"\A#\s+.*?\n+", "", body, count=1)

    slug = {
        "hashing.md": "hashing",
        "troubleshooting.md": "troubleshooting",
        "php-laravel.md": "php-laravel",
        "nodejs-express.md": "nodejs-express",
        "raw-http.md": "raw-http",
        "testing-and-golive.md": "testing",
    }

    def link(m):
        target = slug.get(m.group(1))
        if not target or "/%s/" % target == self_permalink:
            return m.group(0)
        return "[`%s`](../%s/)" % (m.group(1), target)

    # `references/hashing.md` and bare `hashing.md` in prose
    body = re.sub(r"`references/([a-z-]+\.md)`", link, body)
    body = re.sub(r"`([a-z-]+\.md)`", link, body)
    return body.rstrip() + "\n"


def build():
    os.makedirs(DOCS, exist_ok=True)
    written = {}
    for src, permalink, title, desc, lede in PAGES:
        if not os.path.exists(src):
            sys.exit("missing source: %s" % src)
        rel = os.path.relpath(src, ROOT).replace(os.sep, "/")
        fm = [
            "---",
            BANNER,
            "title: %s" % yaml_quote(title),
            "description: %s" % yaml_quote(desc),
            "permalink: %s" % permalink,
            "source: %s" % rel,
        ]
        if lede:
            fm.append("lede: %s" % yaml_quote(lede))
        fm.append("---")
        out = "\n".join(fm) + "\n\n" + transform(read(src), permalink)
        name = permalink.strip("/") + ".md"
        written[name] = out
    return written


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/ does not match the sources")
    args = ap.parse_args()

    pages = build()
    stale = []
    for name, content in sorted(pages.items()):
        path = os.path.join(DOCS, name)
        current = read(path) if os.path.exists(path) else None
        if current == content:
            status = "unchanged"
        else:
            status = "STALE" if args.check else "written"
            stale.append(name)
            if not args.check:
                io.open(path, "w", encoding="utf-8", newline="\n").write(content)
        print("  %-22s %s" % (name, status))

    if args.check and stale:
        print("\ndocs/ is out of date with the reference sources: %s" % ", ".join(stale))
        print("Run: python3 tools/build_docs.py")
        return 1
    print("\n%d page(s), %d changed" % (len(pages), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
