#!/usr/bin/env python3
"""Generate the just-the-docs site in docs/ from the skill's reference files.

The skill files are the single source of truth; docs/ is generated so the two
can never drift. CI runs this with --check and fails if they have.

A note on titles. just-the-docs (0.12) uses `title` for BOTH the sidebar label
and, via jekyll-seo-tag, the <title> tag - it has no separate nav label. A long
keyword-rich title wrecks the sidebar; a short one weakens the search snippet.
The compromise here is short human titles plus a `description` written against
the phrases people actually search when an integration breaks ("hash mismatch",
"paid but not fulfilled"), since that is what fills the snippet under the link.

Each page also carries an `image` (its Open Graph card, from
tools/build_og_images.py) and a `last_modified_at`. That date is PRESERVED when
the body has not changed and only moves when the content actually does - if it
were derived from git or from today it would flip on every run and --check
would never be green. jekyll-sitemap publishes it as <lastmod> and the
structured data as dateModified.

    python3 tools/build_docs.py          # regenerate
    python3 tools/build_docs.py --check  # exit 1 if docs/ is stale (used by CI)
"""

import argparse
import datetime
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFS = os.path.join(ROOT, "paynow-skills", "paynow-integration", "references")
DOCS = os.path.join(ROOT, "docs")
REPO = "https://github.com/67even/paynow-integration-skill"

BANNER = "# GENERATED by tools/build_docs.py - edit the source file, then re-run it."
DATE_TOKEN = "@@LAST_MODIFIED@@"
# First release, per CHANGELOG 1.0.0. `date` is what makes jekyll-seo-tag
# emit og:type=article and the article:published_time/modified_time pair.
PUBLISHED = "2026-09-20"

# source file, permalink, nav title, nav_order, meta description, optional lede
#
# nav_order starts at 3: docs/index.md is 1 and docs/install.md is 2, and both
# are hand-written rather than generated from a reference file. Inserting a page
# above these means renumbering here AND leaving the hand-written ones alone.
PAGES = [
    (
        "troubleshooting.md", "/troubleshooting/", "Troubleshooting", 3,
        "Symptom-to-cause table for Paynow Zimbabwe: hash mismatches, callbacks that "
        "never arrive, and orders marked paid that are never fulfilled.",
        "Start here when something is broken. Most Paynow problems are one of about a "
        "dozen things, and the symptom usually points straight at the cause.",
    ),
    (
        "hashing.md", "/hashing/", "Hashing & signatures", 4,
        "Why Paynow hashes mismatch and how to fix it: field order, URL-decoding, "
        "hashing every returned value, and lower-casing the integration key.",
        "Almost every “Paynow isn’t working” report is a hashing bug. Prove the "
        "helper against the two fixtures below and the whole class of failure disappears.",
    ),
    (
        "php-laravel.md", "/php-laravel/", "PHP & Laravel", 5,
        "Integrating Paynow in PHP and Laravel: the SDK's API, the exceptions it throws, "
        "why paid() does not mean paid, and complete controller wiring.",
        None,
    ),
    (
        "nodejs-express.md", "/nodejs-express/", "Node.js & Express", 6,
        "Integrating Paynow in Node.js and Express: why status.paid() throws, why "
        "pollTransaction must be awaited, and a raw client for InnBucks.",
        None,
    ),
    (
        "raw-http.md", "/raw-http/", "HTTP API reference", 7,
        "The Paynow Zimbabwe HTTP interface for any language: endpoints, request fields, "
        "status values, Express Checkout and the status-update callback.",
        "Use this for any language without an official SDK, and for the Express Checkout "
        "methods the PHP and Node SDKs don’t wrap.",
    ),
    (
        "testing-and-golive.md", "/testing/", "Testing & go-live", 8,
        "Testing Paynow: the merchant-account rule that blocks your own test payments, "
        "the four EcoCash test numbers, card tokens, and the go-live checklist.",
        None,
    ),
]

SLUGS = {src: permalink.strip("/") for src, permalink, _, _, _, _ in PAGES}


def read(path):
    return io.open(path, encoding="utf-8").read().replace("\r\n", "\n")


def q(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def transform(body, self_permalink, title):
    """Restate the H1 from `title`, and turn the references' backticked file
    mentions into links a reader can follow.

    The H1 used to be stripped here, on the assumption that just-the-docs
    renders page.title as one. It does not - its default layout emits
    {{ content }} and nothing else, so every page shipped without an H1 at all.
    The source heading is replaced rather than kept so that the H1, the <title>
    and the sidebar label are the same words."""
    body = re.sub(r"\A#\s+.*?\n+", "", body, count=1)
    body = "# %s\n\n%s" % (title, body)

    def link(m):
        target = SLUGS.get(m.group(1))
        if not target or "/%s/" % target == self_permalink:
            return m.group(0)
        return "[`%s`](../%s/)" % (m.group(1), target)

    body = re.sub(r"`references/([a-z-]+\.md)`", link, body)
    body = re.sub(r"`([a-z-]+\.md)`", link, body)
    return body.rstrip() + "\n"


def build():
    pages = {}
    for src, permalink, title, order, desc, lede in PAGES:
        path = os.path.join(REFS, src)
        if not os.path.exists(path):
            sys.exit("missing source: %s" % path)
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")

        slug = permalink.strip("/")
        fm = ["---", BANNER,
              "title: %s" % q(title),
              "nav_order: %d" % order,
              "permalink: %s" % permalink,
              "description: %s" % q(desc),
              "date: %s" % PUBLISHED,
              "last_modified_at: %s" % DATE_TOKEN,
              # seo-tag would otherwise call a reference page a BlogPosting
              # (because it now has a date). Its block stays a plain WebPage;
              # the rich TechArticle comes from _includes/head_custom.html.
              "seo:",
              "  type: WebPage",
              # jekyll-seo-tag turns this into og:image, og:image:width/height/alt
              # and flips the Twitter card to summary_large_image.
              "image:",
              "  path: /assets/og/%s.png" % slug,
              "  width: 1200",
              "  height: 630",
              "  alt: %s" % q("%s - Paynow Integration Skill" % title),
              "source_file: %s" % rel]
        if lede:
            fm.append("lede: %s" % q(lede))
        fm.append("---")

        body = transform(read(path), permalink, title)
        lede_html = ""
        if lede:
            lede_html = '\n{: .fs-5 .fw-300 }\n%s\n{: .no_toc }\n' % lede

        footer = (
            "\n\n---\n\n"
            "This page is generated from "
            "[`%s`](%s/blob/main/%s) in the skill. "
            "Spotted something wrong? [Open an issue](%s/issues).\n"
            % (rel, REPO, rel, REPO)
        )

        pages[permalink.strip("/") + ".md"] = "\n".join(fm) + "\n\n" + body + footer
    return pages


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/ does not match the sources")
    args = ap.parse_args()

    os.makedirs(DOCS, exist_ok=True)
    pages = build()
    today = datetime.date.today().isoformat()
    stale = []
    for name, template in sorted(pages.items()):
        path = os.path.join(DOCS, name)
        current = read(path) if os.path.exists(path) else None

        # Reuse the recorded date first: if everything else matches, the page
        # has not changed and its last_modified_at must not move.
        previous = ""
        if current:
            m = re.search(r"^last_modified_at:\s*(\S+)\s*$", current, re.M)
            previous = m.group(1) if m else ""
        content = template.replace(DATE_TOKEN, previous or today)

        if current == content:
            state = "unchanged"
        else:
            content = template.replace(DATE_TOKEN, today)
            state = "STALE" if args.check else "written"
            stale.append(name)
            if not args.check:
                io.open(path, "w", encoding="utf-8", newline="\n").write(content)
        print("  %-22s %s" % (name, state))

    if args.check and stale:
        print("\ndocs/ is out of date with the reference sources: %s" % ", ".join(stale))
        print("Run: python3 tools/build_docs.py")
        return 1
    print("\n%d page(s), %d changed" % (len(pages), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
